### ISSUE TITLE
Check that all rooms are playable

### ISSUE THREAD

**Issue by bradleyknaysi** [petertran-21/untitled-ghost-game#65]
# Plan
### Beach if we have time

**Comment by jperez913** [comment]
I've been trying to play through the game a bit. Should this be done on the "master branch?" Looks like there's a test version of the boss from the mountain in the forest hub so just wanna make sure I'm looking at the right branch.

**Comment by bradleyknaysi** [comment]
I would say do testing on the `stable_master` branch

**Comment by jperez913** [comment]
I see. So for this ticket, just making sure each room is playable, `master` is fine? Or should I be checking for playability on `stable_master`? Thanks btw!

**Comment by jliao13** [comment]
Swamp room should now be playable. (all except for swamp boss)

**Comment by jliao13** [comment]
swampBoss room is now playable. Mountain region is mostly playable (miniscule testing left which Josh is dealing with). Memleak problem with bosses in swamp and forest are resolved and do not affect leaving the room. This change was made on swamp branch.

**Comment by bradleyknaysi** [comment]
fairly done
